apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: python
  name: python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python
    spec:
      containers:
      - image: python
        name: python
        resources: {}
        command: ['sh', '-c', 'echo The app is running! && sleep 3600']
        livenessProbe:
          exec:
            command:
            - python
            - -c
            - "import time,urllib.request,random; time.sleep(random.randrange(10,60));resp=urllib.request.urlopen('http://nginx2.default.svc.cluster.local')"
          initialDelaySeconds: 10
          periodSeconds: 10
status: {}
