apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - '$SLEEP_TIME=$(shuf -i 0-30 -n 1);sleep $SLEEP_TIME; curl --max-time 15 -f nginx2.default.svc.cluster.local'
          initialDelaySeconds: 10
          periodSeconds: 5
status: {}
