# syntax=docker/dockerfile:1
FROM golang:1.17 AS builder
WORKDIR /go/src/app
COPY main.go    ./
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app ./main.go

FROM alpine:latest  
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /go/src/app ./
CMD ["./app"]
EXPOSE 80